"""
Smart Dairy ERP — Server-Rendered Pages
=======================================
Serves the multi-page Jinja2 template system (templates/).

Routes are read from `backend/pages_manifest.json` (generated by
`scripts/generate_templates.py`) so the blueprint stays in sync with the
template tree. Access is gated by JWT:

  * Auth pages (/login, /forgot-password, ...)   — public
  * Admin pages (layout=admin)                   — ADMIN only
  * Branch pages (layout=branch)                 — BRANCH_MANAGER (and ADMIN
                                                   where explicitly required)
  * Farmer pages (layout=farmer)                 — FARMER only
  * Shared pages (layout=shared)                 — any authenticated user

Route protection is enforced server-side in addition to the sidebar
visibility: a user who reaches a page outside their role is redirected to
/unauthorized, and every backend API behind it re-checks the role anyway.

The user is resolved from the `access_token` cookie (set on login) or the
`Authorization` header. A missing/expired token redirects to /login.
"""
import json
import os

from flask import Blueprint, render_template, redirect, url_for, request

pages_bp = Blueprint('pages', __name__)

_MANIFEST_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                              'pages_manifest.json')

# Public (no-auth) pages.
# /login serves the SPA shell — the SPA login page is the canonical sign-in
# surface (role tabs, forgot-password + change-password modals). The remaining
# auth helper pages stay server-rendered (they are error/reset helpers).
AUTH_PAGES = {
    '/login': None,  # None -> render the SPA shell (index.html)
    '/forgot-password': 'auth/forgot_password.html',
    '/verify-otp': 'auth/verify_otp.html',
    '/reset-password': 'auth/reset_password.html',
    '/change-password': 'auth/change_password.html',
    '/account-locked': 'auth/account_locked.html',
    '/unauthorized': 'auth/unauthorized.html',
}

# Layout → allowed roles. The system uses exactly three roles:
#   ADMIN, BRANCH_MANAGER, FARMER.
ROLE_MAP = {
    'admin': ('ADMIN',),
    'branch': ('ADMIN', 'BRANCH_MANAGER'),
    'farmer': ('FARMER',),
    'shared': None,  # any authenticated user
}


def _load_manifest():
    """Load the route → template manifest ({} if missing)."""
    try:
        with open(_MANIFEST_PATH, encoding='utf-8') as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


def _user_from_request():
    """Resolve the current user from cookie or Authorization header."""
    # 1) access_token cookie (set on login)
    token = request.cookies.get('access_token')
    if not token:
        # 2) Authorization: Bearer <token>
        auth = request.headers.get('Authorization', '')
        if auth.lower().startswith('bearer '):
            token = auth[7:].strip()
    if not token:
        return None
    try:
        from flask_jwt_extended import decode_token
        import json as _json
        payload = decode_token(token)
        raw = payload.get('sub')
        if isinstance(raw, str):
            try:
                return _json.loads(raw)
            except ValueError:
                return {'uid': raw, 'username': str(raw), 'role': 'UNKNOWN'}
        return raw
    except Exception:
        return None


# ── Register public auth pages ──
for _route, _tpl in AUTH_PAGES.items():
    if _tpl is None:
        def _spa_view():
            return render_template('index.html')
        pages_bp.add_url_rule(_route, endpoint='auth_login', view_func=_spa_view)
        continue
    def _auth_view(tpl=_tpl):
        return render_template(tpl)
    pages_bp.add_url_rule(_route,
                          endpoint='auth_' + _tpl.split('/')[-1].split('.')[0],
                          view_func=_auth_view)

# ── Register manifest pages (role-gated) ──
# Since the SPA (templates/index.html) is the single canonical frontend,
# every role-gated deep link serves the SPA shell. The route is still
# authenticated and role-checked server-side — only the view layer is shared.
for _route, _meta in _load_manifest().items():
    _layout = _meta.get('layout', 'shared')
    _allowed = ROLE_MAP.get(_layout, None)

    def _page_view(roles=_allowed, route_path=_route):
        user = _user_from_request()
        if not user:
            return redirect(url_for('pages.auth_login'))
        if roles and user.get('role') not in roles:
            return redirect(url_for('pages.auth_unauthorized'))
        return render_template('index.html')

    _endpoint = 'page_' + _route.strip('/').replace('/', '_').replace('-', '_')
    pages_bp.add_url_rule(_route, endpoint=_endpoint, view_func=_page_view)

# ── Dynamic routes (not expressible in the static manifest) ──
# Farmer grievance detail — /farmer/grievance/<id> renders the same
# grievance page; the JS reads the id from the URL and loads the detail
# (server-scoped to the authenticated farmer).


def _grievance_view(gid):
    user = _user_from_request()
    if not user:
        return redirect(url_for('pages.auth_login'))
    if user.get('role') != 'FARMER':
        return redirect(url_for('pages.auth_unauthorized'))
    # The SPA grievance page reads the id from the URL hash and loads the
    # detail (server-scoped to the authenticated farmer).
    return render_template('index.html')


pages_bp.add_url_rule('/farmer/grievance/<int:gid>',
                      endpoint='page_farmer_grievance_detail',
                      view_func=_grievance_view)
