"""
Smart Dairy ERP — Server-Rendered Pages
=======================================
Serves the multi-page Jinja2 template system (templates/).

Routes are read from `backend/pages_manifest.json` (generated by
`scripts/generate_templates.py`) so the blueprint stays in sync with the
template tree. Access is gated by JWT:

  * Auth pages (/login, /forgot-password, ...)   — public
  * Admin pages (layout=admin)                   — SUPER_ADMIN, HEAD_OFFICE
  * Branch pages (layout=branch)                 — SUPER_ADMIN, HEAD_OFFICE,
                                                   BRANCH_MANAGER, OPERATOR
  * Farmer pages (layout=farmer)                 — FARMER (and global roles)
  * Shared pages (layout=shared)                 — any authenticated user

The user is resolved from the `access_token` cookie (set on login) or the
`Authorization` header. A missing/expired token redirects to /login.
"""
import json
import os

from flask import Blueprint, render_template, redirect, url_for, request

from backend.models import Farmer as FarmerModel

pages_bp = Blueprint('pages', __name__)

_MANIFEST_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                              'pages_manifest.json')

# Public (no-auth) pages
AUTH_PAGES = {
    '/login': 'auth/login.html',
    '/forgot-password': 'auth/forgot_password.html',
    '/verify-otp': 'auth/verify_otp.html',
    '/reset-password': 'auth/reset_password.html',
    '/change-password': 'auth/change_password.html',
    '/account-locked': 'auth/account_locked.html',
    '/unauthorized': 'auth/unauthorized.html',
}

# Layout → allowed roles
ROLE_MAP = {
    'admin': ('SUPER_ADMIN', 'HEAD_OFFICE'),
    'branch': ('SUPER_ADMIN', 'HEAD_OFFICE', 'BRANCH_MANAGER', 'OPERATOR'),
    'farmer': ('FARMER', 'SUPER_ADMIN', 'HEAD_OFFICE', 'BRANCH_MANAGER', 'OPERATOR'),
    'shared': None,  # any authenticated user
}


def _load_manifest():
    """Load the route → template manifest ({} if missing)."""
    try:
        with open(_MANIFEST_PATH, encoding='utf-8') as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


def _user_from_request():
    """Resolve the current user from cookie or Authorization header."""
    # 1) access_token cookie (set on login)
    token = request.cookies.get('access_token')
    if not token:
        # 2) Authorization: Bearer <token>
        auth = request.headers.get('Authorization', '')
        if auth.lower().startswith('bearer '):
            token = auth[7:].strip()
    if not token:
        return None
    try:
        from flask_jwt_extended import decode_token
        import json as _json
        payload = decode_token(token)
        raw = payload.get('sub')
        if isinstance(raw, str):
            try:
                return _json.loads(raw)
            except ValueError:
                return {'uid': raw, 'username': str(raw), 'role': 'UNKNOWN'}
        return raw
    except Exception:
        return None


def _home_for(user):
    """Default landing page for a user role."""
    role = (user or {}).get('role')
    if role in ('BRANCH_MANAGER', 'OPERATOR'):
        return '/branch/dashboard'
    if role == 'FARMER':
        return '/farmer/profile'
    return '/admin/dashboard'


# ── Register public auth pages ──
for _route, _tpl in AUTH_PAGES.items():
    def _auth_view(tpl=_tpl):
        return render_template(tpl)
    pages_bp.add_url_rule(_route,
                          endpoint='auth_' + _tpl.split('/')[-1].split('.')[0],
                          view_func=_auth_view)

# ── Register manifest pages (role-gated) ──
for _route, _meta in _load_manifest().items():
    _tpl = _meta.get('template', '')
    _layout = _meta.get('layout', 'shared')
    _title = _meta.get('title', '')
    _section = _meta.get('section', '')
    _page_key = _meta.get('page', '')
    _allowed = ROLE_MAP.get(_layout, None)

    def _page_view(tpl=_tpl, roles=_allowed, route_path=_route,
                   p_title=_title, p_section=_section, p_page=_page_key):
        user = _user_from_request()
        if not user:
            return redirect(url_for('pages.auth_login'))
        if roles and user.get('role') not in roles:
            return redirect(url_for('pages.auth_unauthorized'))
        # Farmer portal: resolve the Farmer record so templates can render
        # the farmer's own profile, passbook, livestock and bank details.
        farmer = None
        if user.get('role') == 'FARMER':
            if user.get('farmerId'):
                farmer = FarmerModel.query.get(user.get('farmerId'))
            if not farmer and user.get('farmerCode'):
                farmer = FarmerModel.query.filter_by(farmer_code=user.get('farmerCode')).first()
        return render_template(
            tpl,
            current_user=user,
            farmer=farmer,
            breadcrumb_title=p_title,
            active_page=p_page,
            active_section=p_section,
            home_url=_home_for(user),
        )

    _endpoint = 'page_' + _route.strip('/').replace('/', '_').replace('-', '_')
    pages_bp.add_url_rule(_route, endpoint=_endpoint, view_func=_page_view)
